"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";
import { ArrowLeft, ArrowRight, Check, MessageCircleMore, Volume2 } from "lucide-react";
import "./vocabulary.css";

type Insight={id?:string;original_text:string|null;corrected_text:string|null;tip:string|null;skill_category:string|null;created_at:string};
type Mastery={attempts:number;successes:number;lastScore:number;lastPracticed:string;status:"new"|"learning"|"review"|"mastered"};
const STORE="speakflow:vocabulary-mastery";
function isVocabulary(value:string|null){const v=(value||"").toLowerCase();return v.includes("vocab")||v.includes("word")||v.includes("lex")||v.includes("expression")||v.includes("phrase")}
function focusText(item:Insight){return (item.corrected_text||item.original_text||"New expression").trim()}
function keyFor(item:Insight){return item.id||focusText(item).toLowerCase()}
function label(s:Mastery["status"]){return s==="mastered"?"Dominado":s==="review"?"Revisar":s==="learning"?"Aprendendo":"Novo"}
function nextMastery(old?:Mastery):Mastery{const attempts=(old?.attempts||0)+1,successes=(old?.successes||0)+1;return{attempts,successes,lastScore:100,lastPracticed:new Date().toISOString(),status:successes>=3?"mastered":successes>=2?"review":"learning"}}

export default function VocabularyPage(){
 const router=useRouter();const [items,setItems]=useState<Insight[]>([]);const [hasActivePro,setHasActivePro]=useState(false);const [loading,setLoading]=useState(true);const [active,setActive]=useState(0);const [speaking,setSpeaking]=useState(false);const [mastery,setMastery]=useState<Record<string,Mastery>>({});
 useEffect(()=>{try{setMastery(JSON.parse(localStorage.getItem(STORE)||"{}"))}catch{};(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){router.replace("/login");return}const [{data,error},{data:accessData}]=await Promise.all([supabase.rpc("get_lab_insights",{p_lab:"vocabulary"}),supabase.rpc("get_account_access")]);const access=Array.isArray(accessData)?accessData[0]:accessData;setHasActivePro(access?.effective_plan==="pro");if(error){console.error("Erro ao carregar vocabulary lab:",error);setLoading(false);return;}setItems((data||[]).filter(x=>isVocabulary(x.skill_category)));setLoading(false)})()},[router]);
 const unique=useMemo(()=>{const seen=new Set<string>();return items.filter(x=>{const k=focusText(x).toLowerCase();if(seen.has(k))return false;seen.add(k);return true})},[items]);const current=unique[active]||null;const currentMastery=current?mastery[keyFor(current)]:undefined;
 function save(next:Record<string,Mastery>){setMastery(next);localStorage.setItem(STORE,JSON.stringify(next))}
 function practiced(){if(!current)return;const k=keyFor(current);save({...mastery,[k]:nextMastery(mastery[k])})}
 async function speak(text:string){if(!text||speaking)return;setSpeaking(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error();const res=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/speakflow-voice`,{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,apikey:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,"Content-Type":"application/json"},body:JSON.stringify({text})});if(!res.ok)throw new Error();const url=URL.createObjectURL(await res.blob());const audio=new Audio(url);const done=()=>{URL.revokeObjectURL(url);setSpeaking(false)};audio.addEventListener("ended",done,{once:true});audio.addEventListener("error",done,{once:true});await audio.play()}catch{setSpeaking(false)}}
 if(loading)return <main className="vocab-shell"><p className="vocab-loading">Preparando seu vocabulário…</p></main>;
 return <main className="vocab-shell"><header className="vocab-top"><button onClick={()=>router.push("/")}><ArrowLeft /> Início</button><div className="vocab-brand"><img src="/speakflow-logo.png" alt=""/><strong>Speak<span>Flow</span></strong><small>VOCABULARY LAB</small></div><button onClick={()=>router.push("/progress")}>Progresso <ArrowRight /></button></header>
 <section className="vocab-hero"><div className={`vocab-plan-note ${hasActivePro?"pro":""}`}><span>{hasActivePro?"PRO · LAB COMPLETO":"FREE · SELEÇÃO ESSENCIAL"}</span>{!hasActivePro&&<button type="button" onClick={()=>router.push("/plans")}>Conhecer Pro <ArrowRight /></button>}</div><span>PERSONAL VOCABULARY ENGINE</span><h1>Palavras que nasceram<br/><em>do seu inglês.</em></h1><p>O Vocabulary Lab transforma descobertas das suas conversas em material de estudo pessoal.</p><div><strong>{unique.length}</strong><span>itens do seu repertório</span></div></section>
 {unique.length===0?<section className="vocab-empty"><span>SEU VOCABULÁRIO COMEÇA NA CONVERSA</span><h2>Ainda não encontramos palavras para revisar.</h2><p>Converse naturalmente com o Coach. Conforme o SpeakFlow identifica novas palavras e escolhas de vocabulário, elas aparecem aqui.</p><button onClick={()=>router.push("/coach")}>Conversar com o Coach</button></section>:
 <section className="vocab-workspace"><aside><span>SEU REPERTÓRIO</span>{unique.map((item,i)=>{const m=mastery[keyFor(item)];return <button key={item.id||i} className={i===active?"active":""} onClick={()=>setActive(i)}><strong>{focusText(item)}</strong><small>{label(m?.status||"new")}</small></button>})}</aside>
 {current&&<article className="vocab-study"><div className="vocab-mastery"><span>{label(currentMastery?.status||"new")}</span><strong>{currentMastery?.successes||0}/3 práticas</strong></div><span>EM ESTUDO</span><h2>{focusText(current)}</h2>{current.original_text&&current.corrected_text&&current.original_text!==current.corrected_text&&<div className="vocab-origin"><small>NA SUA CONVERSA</small><p>{current.original_text}</p></div>}<div className="vocab-note"><small>INSIGHT DO COACH</small><p>{current.tip||"Revise esta expressão e use-a em uma nova frase para consolidar seu aprendizado."}</p></div><div className="vocab-actions"><button onClick={()=>speak(focusText(current))} disabled={speaking}>{speaking?"Reproduzindo…":<><Volume2 /> Ouvir com SpeakFlow</>}</button><button onClick={practiced}><Check /> Pratiquei esta expressão</button><button onClick={()=>router.push("/coach")}><MessageCircleMore /> Usar em uma conversa</button></div></article>}</section>}
 </main>
}