"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";
import { ChartNoAxesColumnIncreasing, House, MessageCircleMore } from "lucide-react";
import "./progress.css";

type Progress = { conversations_count:number; total_minutes:number; streak_days:number; last_practice_date:string|null };
type LearningSession = { id?:string; mode:string|null; duration_seconds:number|null; score?:number|null; summary:string|null; skills_practiced:string|null; positive_point:string|null; improvement_point:string|null; next_recommendation:string|null; created_at:string };
type LearningInsight = { id?:string; level:string|null; original_text:string|null; corrected_text:string|null; tip:string|null; skill_category:string|null; created_at:string };
type LearningPlan = { primary_goal:string|null; priority_skills:string|null; current_focus:string|null; next_milestone:string|null; coach_strategy:string|null; updated_at:string|null };

const emptyProgress: Progress = { conversations_count:0,total_minutes:0,streak_days:0,last_practice_date:null };

function formatDate(value:string|null){if(!value)return "Ainda não registrada";return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value))}
function formatDuration(seconds:number|null){return `${Math.max(1,Math.round((seconds??0)/60))} min`}

export default function ProgressPage(){
 const router=useRouter();
 const [progress,setProgress]=useState<Progress>(emptyProgress);
 const [sessions,setSessions]=useState<LearningSession[]>([]);
 const [insights,setInsights]=useState<LearningInsight[]>([]);
 const [learningPlan,setLearningPlan]=useState<LearningPlan|null>(null);
 const [loading,setLoading]=useState(true);
 const [errorMessage,setErrorMessage]=useState("");

 useEffect(()=>{async function load(){
  const {data:{user},error:userError}=await supabase.auth.getUser();
  if(userError || !user){router.replace("/login");return}
  const [p,s,i,lp]=await Promise.all([
   supabase.from("progress").select("conversations_count, total_minutes, streak_days, last_practice_date").eq("user_id",user.id).single(),
   supabase.from("learning_sessions").select("id, mode, duration_seconds, score, summary, skills_practiced, positive_point, improvement_point, next_recommendation, created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(30),
   supabase.from("learning_insights").select("id, level, original_text, corrected_text, tip, skill_category, created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(30),
   supabase.from("learning_plans").select("primary_goal, priority_skills, current_focus, next_milestone, coach_strategy, updated_at").eq("user_id",user.id).maybeSingle()
  ]);
  if(p.data)setProgress(p.data); if(s.data)setSessions(s.data); if(i.data)setInsights(i.data); if(lp.data)setLearningPlan(lp.data);
  if(p.error||s.error||i.error||lp.error){console.error("Erro ao carregar progresso:",{progress:p.error,sessions:s.error,insights:i.error,learningPlan:lp.error});setErrorMessage("Parte dos seus dados não pôde ser carregada agora.")}
  setLoading(false);
 }load()},[router]);

 const skills=useMemo(()=>{const normalizeSkill=(value:string|null)=>{const raw=value?.trim().toLowerCase()||"";if(!raw)return "Outros";if(raw.includes("pronun")||raw.includes("pronunciation"))return "Pronúncia";if(raw.includes("gram")||raw.includes("grammar")||raw.includes("past_tense")||raw.includes("past tense")||raw.includes("present_tense")||raw.includes("present tense")||raw.includes("future_tense")||raw.includes("future tense")||raw.includes("verb")||raw.includes("tense"))return "Gramática";if(raw.includes("vocab")||raw.includes("word choice"))return "Vocabulário";if(raw.includes("flu")||raw.includes("fluency"))return "Fluência";if(raw.includes("listen")||raw.includes("compreens"))return "Compreensão";if(raw.includes("speak")||raw.includes("conversation")||raw.includes("conversa"))return "Conversação";return "Outros"};const m=new Map<string,number>();insights.forEach(x=>{const c=normalizeSkill(x.skill_category);m.set(c,(m.get(c)??0)+1)});return Array.from(m.entries()).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count)},[insights]);
 const maxSkill=Math.max(1,...skills.map(x=>x.count));
 const skillEvolution=useMemo(()=>{const now=Date.now();const recentCutoff=now-7*24*60*60*1000;const previousCutoff=now-14*24*60*60*1000;const normalize=(value:string|null)=>{const raw=value?.trim().toLowerCase()||"";if(!raw)return "Outros";if(raw.includes("pronun")||raw.includes("pronunciation"))return "Pronúncia";if(raw.includes("gram")||raw.includes("grammar")||raw.includes("past_tense")||raw.includes("past tense")||raw.includes("present_tense")||raw.includes("present tense")||raw.includes("future_tense")||raw.includes("future tense")||raw.includes("verb")||raw.includes("tense"))return "Gramática";if(raw.includes("vocab")||raw.includes("word choice"))return "Vocabulário";if(raw.includes("flu")||raw.includes("fluency"))return "Fluência";if(raw.includes("listen")||raw.includes("compreens"))return "Compreensão";if(raw.includes("speak")||raw.includes("conversation")||raw.includes("conversa"))return "Conversação";return "Outros"};const map=new Map<string,{recent:number;previous:number}>();insights.forEach(x=>{const time=new Date(x.created_at).getTime();const name=normalize(x.skill_category);const entry=map.get(name)??{recent:0,previous:0};if(time>=recentCutoff)entry.recent+=1;else if(time>=previousCutoff)entry.previous+=1;map.set(name,entry)});return map},[insights]);
 const activity=useMemo(()=>{const days=Array.from({length:7},(_,n)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(6-n));return{key:d.toISOString().split("T")[0],label:new Intl.DateTimeFormat("pt-BR",{weekday:"short"}).format(d).replace(".",""),minutes:0}});sessions.forEach(x=>{const k=new Date(x.created_at).toISOString().split("T")[0];const d=days.find(y=>y.key===k);if(d)d.minutes+=(x.duration_seconds??0)/60});days.forEach(d=>{d.minutes=Math.round(d.minutes)});return days},[sessions]);
 const maxActivity=Math.max(1,...activity.map(x=>x.minutes));
 const sessionTotalSeconds=sessions.reduce((sum,x)=>sum+Math.max(0,x.duration_seconds??0),0);
 const sessionTotalMinutes=Math.round(sessionTotalSeconds/60);
 const sessionCount=sessions.length;
 const modeSummary=useMemo(()=>{const summary={conversation:{sessions:0,seconds:0},vocabulary:{sessions:0,seconds:0},pronunciation:{sessions:0,seconds:0},musiclab:{sessions:0,seconds:0}};sessions.forEach(x=>{const key=x.mode==="vocabulary"?"vocabulary":x.mode==="pronunciation"?"pronunciation":x.mode==="conversation"?"conversation":x.mode==="musiclab"?"musiclab":null;if(!key)return;summary[key].sessions+=1;summary[key].seconds+=Math.max(0,x.duration_seconds??0)});return summary},[sessions]);
 const avg=sessions.length?Math.max(1,Math.round(sessions.reduce((a,x)=>a+(x.duration_seconds??0),0)/sessions.length/60)):0;
 const musicLabStats=useMemo(()=>{const music=sessions.filter(x=>x.mode==="musiclab");const scored=music.filter(x=>typeof x.score==="number");const average=scored.length?Math.round(scored.reduce((sum,x)=>sum+(x.score??0),0)/scored.length):0;const insightsCount=insights.filter(x=>(x.skill_category??"").toLowerCase().includes("musiclab")).length;return{sessions:music.length,minutes:Math.round(music.reduce((sum,x)=>sum+(x.duration_seconds??0),0)/60),average,insights:insightsCount}},[sessions,insights]);
 const smartSummary=useMemo(()=>{if(!sessions.length&&!insights.length)return null;const topSkill=skills[0]?.name??null;const recentSessions=sessions.filter(x=>Date.now()-new Date(x.created_at).getTime()<=7*24*60*60*1000).length;const latestInsight=insights[0]??null;let headline="Seu aprendizado está ganhando forma.";if(topSkill)headline=`${topSkill} é o foco mais presente agora.`;let recommendation="Continue praticando para o SpeakFlow identificar novos padrões no seu aprendizado.";if(topSkill==="Gramática")recommendation="Na próxima conversa, pratique frases completas e variações de tempo verbal para reforçar o padrão que apareceu nos seus insights.";else if(topSkill==="Pronúncia")recommendation="Na próxima prática, priorize respostas faladas e repita construções que exigem mais clareza de pronúncia.";else if(topSkill==="Vocabulário")recommendation="Na próxima conversa, tente reutilizar palavras novas em contextos diferentes para ampliar seu repertório ativo.";else if(topSkill==="Fluência")recommendation="Na próxima prática, tente sustentar respostas um pouco mais longas, mantendo o fluxo natural da conversa.";else if(topSkill==="Conversação")recommendation="Na próxima sessão, explore respostas mais completas e perguntas de continuidade para desenvolver a conversação.";return{headline,recentSessions,topSkill,latestTip:latestInsight?.tip??null,recommendation}},[sessions,insights,skills]);

 return <main className="progress-shell">
  <aside className="progress-sidebar">
   <button className="progress-brand" onClick={()=>router.push("/")}><img src="/speakflow-logo.png" alt="SpeakFlow"/><div><strong>Speak<span>Flow</span></strong><small>AI ENGLISH COACH</small></div></button>
   <nav className="progress-menu"><button onClick={()=>router.push("/")}><span><House /></span>Início</button><button onClick={()=>router.push("/coach")}><span><MessageCircleMore /></span>Coach</button><button className="active"><span><ChartNoAxesColumnIncreasing /></span>Progresso</button></nav>
   <div className="progress-sidebar-footer"><img src="/speakflow-logo.png" alt=""/><div><strong>SpeakFlow</strong><small>Sua evolução, em movimento.</small></div></div>
  </aside>
  <section className="progress-main">
   <header className="progress-topbar"><button className="progress-mobile-brand" onClick={()=>router.push("/")}><img src="/speakflow-logo.png" alt="SpeakFlow"/><strong>Speak<span>Flow</span></strong></button><div className="progress-topbar-spacer"/><button className="progress-coach-link" onClick={()=>router.push("/coach")}>Praticar agora <span>→</span></button></header>
   <div className="progress-content">
    <section className="progress-hero"><div><span className="progress-eyebrow">SEU PROGRESSO</span><h1>Sua evolução.<br/><em>Visível.</em></h1><p>Acompanhe sua constância, suas sessões e os insights que o SpeakFlow identifica ao longo da sua prática.</p></div><div className="progress-hero-mark"><div className="progress-orbit"/><img src="/speakflow-logo.png" alt=""/></div></section>
    {loading?<section className="progress-state">Carregando sua jornada...</section>:<>
     {errorMessage&&<div className="progress-alert">{errorMessage}</div>}
     <section className="progress-metrics">
      <article><span>SESSÕES</span><strong>{sessionCount}</strong><small>conversas concluídas</small></article>
      <article><span>TEMPO TOTAL</span><strong>{sessionTotalMinutes}<b> min</b></strong><small>de prática acumulada</small></article>
      <article><span>SEQUÊNCIA</span><strong>{progress.streak_days}<b> dias</b></strong><small>de constância</small></article>
      <article><span>ÚLTIMA PRÁTICA</span><strong className="metric-date">{formatDate(progress.last_practice_date)}</strong><small>registro mais recente</small></article>
     </section>
     {learningPlan&&<section className="progress-card learning-plan"><div className="learning-plan-heading"><div><span>SEU PLANO DE APRENDIZADO</span><h2>Seu próximo passo, com direção.</h2><p>O SpeakFlow adapta esta rota conforme você pratica e evolui.</p></div><img src="/speakflow-logo.png" alt=""/></div><div className="learning-plan-grid"><article className="learning-plan-goal"><span>OBJETIVO ATUAL</span><h3>{learningPlan.primary_goal}</h3></article><article><span>FOCO AGORA</span><p>{learningPlan.current_focus}</p></article><article><span>PRÓXIMA CONQUISTA</span><p>{learningPlan.next_milestone}</p></article><article><span>DIREÇÃO DO COACH</span><p>{learningPlan.coach_strategy}</p></article></div>{learningPlan.priority_skills&&<div className="learning-plan-skills"><span>HABILIDADES PRIORITÁRIAS</span><p>{learningPlan.priority_skills}</p></div>}</section>}
     <section className="progress-card progress-modes"><div className="progress-card-heading"><div><span>MODOS DE TREINO</span><h2>Sua prática por modalidade</h2></div><small>Baseado nas sessões concluídas</small></div><div className="mode-summary-grid"><article><div className="mode-summary-top"><span>CONVERSAÇÃO</span><b>Speaking</b></div><strong>{modeSummary.conversation.sessions}</strong><p>{modeSummary.conversation.sessions===1?"sessão concluída":"sessões concluídas"} · {Math.round(modeSummary.conversation.seconds/60)} min</p></article><article><div className="mode-summary-top"><span>VOCABULÁRIO</span><b>Vocabulary</b></div><strong>{modeSummary.vocabulary.sessions}</strong><p>{modeSummary.vocabulary.sessions===1?"sessão concluída":"sessões concluídas"} · {Math.round(modeSummary.vocabulary.seconds/60)} min</p></article><article><div className="mode-summary-top"><span>PRONÚNCIA</span><b>Pronunciation</b></div><strong>{modeSummary.pronunciation.sessions}</strong><p>{modeSummary.pronunciation.sessions===1?"sessão concluída":"sessões concluídas"} · {Math.round(modeSummary.pronunciation.seconds/60)} min</p></article><article className="musiclab-mode"><div className="mode-summary-top"><span>MUSICLAB™</span><b>Music × Language</b></div><strong>{modeSummary.musiclab.sessions}</strong><p>{modeSummary.musiclab.sessions===1?"sessão concluída":"sessões concluídas"} · {Math.round(modeSummary.musiclab.seconds/60)} min</p></article></div></section>
     <section className="progress-card progress-musiclab"><div className="progress-card-heading"><div><span>MUSICLAB™ EVOLUTION</span><h2>Listening + Shadowing</h2></div><small>Aprendizado dentro da música</small></div><div className="musiclab-progress-grid"><article><span>SESSÕES</span><strong>{musicLabStats.sessions}</strong><small>experiências concluídas</small></article><article><span>TEMPO</span><strong>{musicLabStats.minutes}<b> min</b></strong><small>imersão musical</small></article><article><span>SHADOW SCORE</span><strong>{musicLabStats.average}<b>%</b></strong><small>média das sessões</small></article><article><span>INSIGHTS</span><strong>{musicLabStats.insights}</strong><small>práticas registradas</small></article></div><div className="musiclab-progress-foot"><div><span>LISTEN</span><i/><span>DISCOVER</span><i/><span>SHADOW</span><i/><span>SPEAK</span></div><button onClick={()=>router.push("/musiclab")}>Entrar no MusicLab <b>→</b></button></div></section>
     <section className="progress-grid">
      <article className="progress-card"><div className="progress-card-heading"><div><span>ATIVIDADE</span><h2>Últimos 7 dias</h2></div><small>Média: {avg} min/sessão</small></div><div className="activity-chart">{activity.map(d=><div className="activity-day" key={d.key}><div className="activity-track"><div className="activity-bar" style={{height:`${Math.max(d.minutes?12:2,(d.minutes/maxActivity)*100)}%`}}/></div><strong>{d.minutes}</strong><span>{d.label}</span></div>)}</div></article>
      <article className="progress-card"><div className="progress-card-heading"><div><span>SPEAKFLOW SKILLS</span><h2>Foco do aprendizado</h2></div></div>{skills.length?<div className="skills-list">{skills.slice(0,6).map(x=>{const trend=skillEvolution.get(x.name);const delta=(trend?.recent??0)-(trend?.previous??0);return <div className="skill-row" key={x.name}><div><strong>{x.name}</strong><span>{x.count} insight{x.count===1?"":"s"} · {delta>0?`+${delta} esta semana`:delta<0?`${delta} vs. semana anterior`:"ritmo estável"}</span></div><div className="skill-track"><i style={{width:`${x.count/maxSkill*100}%`}}/></div></div>})}</div>:<p className="progress-empty">Suas habilidades aparecerão aqui conforme o Coach gerar novos insights.</p>}</article>
     </section>
     {smartSummary&&<section className="progress-card progress-smart"><div className="progress-card-heading"><div><span>SPEAKFLOW INTELLIGENCE</span><h2>Resumo inteligente</h2></div><small>Baseado no seu histórico real</small></div><div className="smart-summary-grid"><div className="smart-summary-main"><span>LEITURA ATUAL</span><h3>{smartSummary.headline}</h3><p>Você concluiu {smartSummary.recentSessions} {smartSummary.recentSessions===1?"sessão":"sessões"} nos últimos 7 dias{smartSummary.topSkill?`, e ${smartSummary.topSkill.toLowerCase()} aparece como seu foco mais recorrente.`:"."}</p></div><div className="smart-summary-next"><span>PRÓXIMO FOCO</span><p>{smartSummary.recommendation}</p>{smartSummary.latestTip&&<small>✦ Insight recente: {smartSummary.latestTip}</small>}</div></div></section>}
     <section className="progress-card progress-insights"><div className="progress-card-heading"><div><span>INSIGHTS RECENTES</span><h2>O que você está aprendendo</h2></div><small>{insights.length} registros recentes</small></div>{insights.length?<div className="insights-grid">{insights.slice(0,6).map((x,n)=><article className="progress-insight" key={x.id??`${x.created_at}-${n}`}><div className="progress-insight-top"><span>{x.skill_category||"Insight"}</span><small>{x.level||"practice"}</small></div>{x.original_text&&<p><b>Você disse</b>{x.original_text}</p>}{x.corrected_text&&<p className="corrected"><b>Forma sugerida</b>{x.corrected_text}</p>}{x.tip&&<div className="progress-tip">✦ {x.tip}</div>}</article>)}</div>:<p className="progress-empty">Conclua novas conversas para construir seu histórico de aprendizado.</p>}</section>
     <section className="progress-card progress-sessions"><div className="progress-card-heading"><div><span>SUA JORNADA</span><h2>Histórico inteligente</h2></div><small>Resumo das sessões concluídas</small></div>{sessions.length?<div className="session-history">{sessions.slice(0,8).map((x,n)=><article className={x.summary?"session-history-card has-summary":"session-history-card"} key={x.id??`${x.created_at}-${n}`}><div className="session-history-top"><div><span className="session-icon">✦</span><div><strong>{x.mode==="conversation"?"Conversação":x.mode==="vocabulary"?"Vocabulário":x.mode==="pronunciation"?"Pronúncia":x.mode==="musiclab"?"MusicLab™":x.mode||"Prática"}</strong><small>{formatDate(x.created_at)} · {formatDuration(x.duration_seconds)}</small></div></div>{x.skills_practiced&&<span className="session-skill">{x.skills_practiced}</span>}</div>{x.summary?<><p className="session-history-summary">{x.summary}</p><div className="session-history-details">{x.positive_point&&<div><span>PONTO POSITIVO</span><p>{x.positive_point}</p></div>}{x.improvement_point&&<div><span>PRÓXIMA EVOLUÇÃO</span><p>{x.improvement_point}</p></div>}</div>{x.next_recommendation&&<div className="session-history-next"><span>✦ RECOMENDAÇÃO DO COACH</span><p>{x.next_recommendation}</p></div>}</>:<p className="session-history-legacy">Sessão registrada antes da introdução dos resumos inteligentes.</p>}</article>)}</div>:<p className="progress-empty">Sua primeira sessão concluída aparecerá aqui.</p>}</section>
    </>}
   </div>
  </section>
 </main>
}
